// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uarwkvtddhrarhcluuhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhcndrdnRkZGhyYXJoY2x1dWhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTA4NDksImV4cCI6MjA3MDIyNjg0OX0.98vq6af863kP5EeiongVB4_a5bXz2qJwCeXFE1w_OQc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});