// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovljohwvxykjgjbaosno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92bGpvaHd2eHlramdqYmFvc25vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NDk1ODIsImV4cCI6MjA3MDIyNTU4Mn0.0i8uQHucYJTDBXSKmgLMVpNENsXITyN2H0kR8XZU0zY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});