// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbdnkfqxxsdutdujjupp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiZG5rZnF4eHNkdXRkdWpqdXBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTAxNTUsImV4cCI6MjA3MDIyNjE1NX0.BnUs4_Qxpn_pQiGo_lPPzNKqlBWFCE3Qyl3TnSMSXyc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});